//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Animals
{
	public virtual object foodNeedsPerDay
	{
		get;
		set;
	}

	public virtual object cageType
	{
		get;
		set;
	}

	public virtual Cage Cage
	{
		get;
		set;
	}

}

