//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tracking
{
	public virtual object FoodOnHand
	{
		get;
		set;
	}

	public virtual AdoptionDesk AdoptionDesk
	{
		get;
		set;
	}

}

